name: learn-github-actions
on: [push]

jobs:
  Install Python:
  - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
  - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
   - name: move to test directory
      run: |
      cd tests
        
   - name: Test with pytest
      run: |
        pytest test.py
